/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kongle (https://sketchfab.com/minecraftnorge)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/mercury-natural-color-bc882b60ec1f4050a1771a54bdb066b1
Title: Mercury natural color
*/

import { a, useSpring } from "@react-spring/three";
import { Html, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { PlanetProps } from "../../utils/Types";
import OrbitTrail from "../OrbitTrail";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
  };
  materials: {
    ["moon.007"]: THREE.MeshStandardMaterial;
  };
};
export default function Mercury({
  size,
  rotationSpeed = 0.01,
  inclination = 0,
  lineColor,
  showOrbit,
  onClick,
  showTooltip,
  orbitPoints,
  position,
  name,
}: PlanetProps) {
  const { nodes, materials } = useGLTF("/models/mercury.glb") as GLTFResult;
  const planetRef = useRef<THREE.Group>(null);
  const [hovered, setHovered] = useState<boolean>(false); // State for hover effect
  // Tooltip visibility
  useFrame(() => {
    if (planetRef.current) {
      planetRef.current.rotation.y += rotationSpeed;
    }
  });

  // Update planet position and inclination
  useEffect(() => {
    if (planetRef.current) {
      planetRef.current.rotation.x += 90;
      planetRef.current.position.set(0, 0, 0);
      planetRef.current.rotation.z = inclination * (Math.PI / 180);
    }
  }, [inclination]);

  // Handle hover state and show tooltip
  const handleHover = (isHovered: boolean) => {
    setHovered(isHovered);
  };

  // React Spring animation for smooth scale effect on hover
  const { scale } = useSpring({
    scale: hovered ? size * 5 : size, // Scale up when hovered
    config: { tension: 300, friction: 30 }, // Adjust animation speed and bounciness
  });
  return (
    <>
      <a.group
        scale={scale}
        onClick={() => onClick()} // Call onClick from props
        onPointerOver={() => handleHover(true)}
        onPointerOut={() => handleHover(false)}
        position={position}
        ref={planetRef}
        dispose={null}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["moon.007"]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </a.group>
      {showOrbit && (
        <OrbitTrail
          onClick={onClick}
          lineColor={lineColor}
          points={orbitPoints}
          hovered={hovered}
          setHovered={handleHover}
        />
      )}

      {/* Tooltip */}

      {showTooltip && (
        <Html position={position} className="w-72">
          <div onClick={onClick} className="tooltip text-white font-bold">
            {name}
          </div>
        </Html>
      )}
    </>
  );
}

useGLTF.preload("/models/mercury.glb");
