/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kongle (https://sketchfab.com/minecraftnorge)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/neptune-8c6dc96f47ab4d798a1cb2d827da3fbe
Title: Neptune
*/

import { a, useSpring } from "@react-spring/three";
import { Html, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { PlanetProps } from "../../utils/Types";
import OrbitTrail from "../OrbitTrail";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
  };
  materials: {
    moon: THREE.MeshStandardMaterial;
  };
};

export default function Neptune({
  size,
  rotationSpeed = 0.01,
  inclination = 0,
  lineColor,
  onClick,
  orbitPoints,
  position,
  name,
}: PlanetProps) {
  const planetRef = useRef<THREE.Mesh>(null);
  const { nodes, materials } = useGLTF("/models/neptune.glb") as GLTFResult;
  const [hovered, setHovered] = useState<boolean>(false);
  const [showTooltip, setShowTooltip] = useState<boolean>(false);

  useFrame(() => {
    if (planetRef.current) {
      planetRef.current.rotation.y += rotationSpeed;
    }
  });

  useEffect(() => {
    if (planetRef.current) {
      planetRef.current.rotation.x += 90;
      planetRef.current.position.set(0, 0, 0);
      planetRef.current.rotation.z = inclination * (Math.PI / 180);
    }
  }, [inclination]);

  const handleHover = (isHovered: boolean) => {
    setHovered(isHovered);
    setShowTooltip(isHovered);
  };

  const { scale } = useSpring({
    scale: hovered ? size * 5 : size,
    config: { tension: 300, friction: 30 },
  });

  return (
    <>
      <a.group
        scale={scale}
        onClick={() => onClick()}
        onPointerOver={() => handleHover(true)}
        onPointerOut={() => handleHover(false)}
        position={position}
        dispose={null}
      >
        <mesh
          ref={planetRef}
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.moon}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </a.group>
      <OrbitTrail
        onClick={onClick}
        lineColor={lineColor}
        points={orbitPoints}
        hovered={hovered}
        setHovered={handleHover}
      />

      {showTooltip && (
        <Html position={planetRef.current?.position} className="w-72">
          <div className="tooltip text-white font-bold">{name}</div>
        </Html>
      )}
    </>
  );
}

useGLTF.preload("/models/neptune.glb");
