/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kongle (https://sketchfab.com/minecraftnorge)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/uranus-b488282fa28344009fa8c8cdb3384456
Title: Uranus
*/

import { a, useSpring } from "@react-spring/three";
import { Html, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { PlanetProps } from "../../utils/Types";
import OrbitTrail from "../OrbitTrail";

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh;
  };
  materials: {
    ["moon.005"]: THREE.MeshStandardMaterial;
  };
};

export default function Uranus({
  size,
  rotationSpeed = 0.01,
  inclination = 0,
  lineColor,
  showOrbit,
  onClick,
  showTooltip,
  orbitPoints,
  position,
  name,
}: PlanetProps) {
  const planetRef = useRef<THREE.Mesh>(null);
  const { nodes, materials } = useGLTF("/models/uranus.glb") as GLTFResult;
  const [hovered, setHovered] = useState<boolean>(false);

  useFrame(() => {
    if (planetRef.current) {
      planetRef.current.rotation.z += rotationSpeed;
    }
  });

  useEffect(() => {
    if (planetRef.current) {
      planetRef.current.rotation.x += 90;
      planetRef.current.position.set(0, 0, 0);
      planetRef.current.rotation.z = inclination * (Math.PI / 180);
    }
  }, [inclination]);

  const handleHover = (isHovered: boolean) => {
    setHovered(isHovered);
  };

  const { scale } = useSpring({
    scale: hovered ? size : size,
    config: { tension: 300, friction: 30 },
  });

  return (
    <>
      <a.group
        scale={scale}
        onClick={() => onClick()}
        onPointerOver={() => handleHover(true)}
        onPointerOut={() => handleHover(false)}
        position={position}
        dispose={null}
      >
        <mesh
          castShadow
          receiveShadow
          ref={planetRef}
          geometry={nodes.Object_3.geometry}
          material={materials["moon.005"]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </a.group>
      {showOrbit && (
        <OrbitTrail
          onClick={onClick}
          lineColor={lineColor}
          points={orbitPoints}
          hovered={hovered}
          setHovered={handleHover}
        />
      )}

      {(showTooltip || hovered) && (
        <Html position={position} className="w-72 cursor-pointer">
          <div onClick={onClick} className="tooltip text-white font-bold">
            {name}
          </div>
        </Html>
      )}
    </>
  );
}

useGLTF.preload("/models/uranus.glb");
