/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-9ef1c68fbb944147bcfcc891d3912645
Title: Sun
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { SunProps } from "../utils/Types";

type GLTFResult = GLTF & {
  nodes: {
    UnstableStarCore_1_0: THREE.Mesh;
    UnstableStarref_2_0: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshStandardMaterial;
    material_1: THREE.MeshPhysicalMaterial;
  };
};

type ActionName = "Take 001";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export default function Sun({ size, intensity, position }: SunProps) {
  // const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF(
    "/models/sun.glb",
  ) as GLTFResult;
  // const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group position={position} scale={size} dispose={null}>
      <spotLight
        angle={0.1}
        penumbra={1.5}
        intensity={1000}
        position={position}
      />
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="3a2aaa22fb3d4b329318a980ad1bf6d1fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="UnstableStarCore" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="UnstableStarCore_1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.UnstableStarCore_1_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="UnstableStarref"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={1.01}
                >
                  <mesh
                    name="UnstableStarref_2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.UnstableStarref_2_0.geometry}
                    material={materials.material_1}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/sun.glb");
